pipeline:
  name: Build gosample
  identifier: Build_wasptree_gosample_1743076560518
  projectIdentifier: Andy_Sutcliffe
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Go App
                  identifier: build_go_app
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
              - step:
                  type: Run
                  name: Package Go App
                  identifier: package_go_app
                  spec:
                    command: |-
                      echo "Package Go App"
                      docker build -t wasptree/example-go-app-<+pipeline.branch>:<+pipeline.variables.version> .
              - step:
                  type: Run
                  name: Push Go App
                  identifier: push_go_app
                  spec:
                    command: ""
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: wasptree/gosample
        build: <+input>
  variables:
    - name: version
      type: String
      description: ""
      required: false
      value: "1.0"
