pipeline:
  name: Build gosample
  identifier: Build_wasptree_gosample_1743076560518
  projectIdentifier: Andy_Sutcliffe
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Go App
                  identifier: build_go_app
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: wasptree/gosample
        build: <+input>
